---
title: "Week 1 Assignment"
author: "Cecilia De La Fuente Chavez"
format: html
editor: visual
---

## Overview

For the Week 1 Assignment, I will be using the [U.S. Energy Information Administration's](https://www.eia.gov/renewable/data.php) *Total energy consumption of renewable and nonrenewable energy sources* data set to examine how the consumption of energy from different sources (Coal, Natural Gas, Petroleum, Nuclear, Hydroelectric, Geothermal, Solar, Wind, Energy, and Biomass) has changed over the years. The data set is an Excel file with two tabs; one with monthly data from 1973 until 2026, and the other annual data from 1949 until 2025. I expect to use the variables related to time; year and possibly month, as well as the different energy sources by type; renewable and non-renewable. I anticipate potentially transforming the data by changing the energy consumption units, currently Quadrillion Btu, to percentages of the total to make it easier to visualize, as well as adding a new column to categorize each energy source by their type for better filtering between renewable and non-renewable sources. My interest in decarbonization efforts in my motivation for selecting this particular data set.
